language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
