language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
  - printf "\n" | pecl install imagick
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
