0:
    cell       : 20
    border     : 1
    caption    : 8
    coordinates: 5
1:
    cell       : 30
    border     : 1
    caption    : 12
    coordinates: 8

2:
    cell       : 60
    border     : 1
    caption    : 24
    coordinates: 14

3:
    cell       : 90
    border     : 1
    caption    : 36
    coordinates: 22
