0:
    texture:
        piece: classic
1:
    texture:
        piece: cheq_tt
2:
    texture:
        piece: alpha
        board: olive
3:
    texture:
        piece: book
        board: wood1
4:
    texture:
        piece: club
        board: wood2
5:
    texture:
        piece: modern
        board: metal
6:
    texture:
        piece: vintage
